Portfolio project
valt19/portfolio-project pull request #1
Opened 2022-12-03 14:12 UTC by valt19

Portfolio-project
I added a CSS file, README.md file , .stylelintrc file, index.html file , .gitignore file , linters file ,package.json file and a hintrc file

2022-12-03 14:18 UTC, amejid reviewed
Hi @valt19 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, where the linter checks are not passing. Kindly do the required things to make the linter checks green.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-05 09:23 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi @valt19 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 
  - Linter checks are are green :+1: 
  - Good use of github flow :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 09:23 UTC, GedeonTS commented on .gitignore
> +/test.md
- [ OPTIONAL] In my opinion, since we don't have test.md in project, kindly remove it :recycle:

2022-12-05 09:23 UTC, GedeonTS commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/trevo-odeke)
- [OPTIONAL] It would be better to put your own handles(i.e @trevor) to make sure the vistitors notice them :recycle:

2022-12-05 09:23 UTC, GedeonTS commented on README.md
> +- [ ] **[new_feature_3]**
- [ ] Kindly describe one or two features that you suppose are going to be added to the project as it's continues :recycle:

2022-12-05 09:23 UTC, GedeonTS commented on index.html
> +        </div>
- [OPTIONAL] In my opinion , it's not necessary to to wrap the logo into a div, i suggest to style the anchor tag itselt :recycle:

2022-12-05 09:23 UTC, GedeonTS commented on index.html
> +        <p class="text">I’m Trevor Glad to see you!</p>
- [ ] Kindly make sure for the main title you use `h1` as recommended by the [HTML/CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) :recycle:

2022-12-05 09:23 UTC, GedeonTS commented on index.html
> +   </a>
- [ ] Why don't you use anchor tag itself for this link, let's use ` <a href="#" class="lets"> `
 ` lets connect`
   `</a> `

2022-12-05 09:23 UTC, GedeonTS commented on style.css
> +  flex-grow: 0;
- [ ] Kindly make sure your header looks like the figma design as much as possible, (font-family ,font-weight,text-decoration, humburger button)

  - Your design:
![nav](https://user-images.githubusercontent.com/97834160/205599737-c3a6e85c-8418-494f-990d-d41cff9efb55.png)


  - Figma:
![navFig](https://user-images.githubusercontent.com/97834160/205599765-b5244b4c-620d-4290-aee5-8a2076472536.png)

2022-12-05 09:23 UTC, GedeonTS commented on style.css
> +  font-style: normal;
- Kinldy make sure your section has the same as the figma design like figma design as recommended be the [project  requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md#:~:text=You%20must%20stick%20to%20the%20design%20as%20much%20as%20possible%20(e.g.%20font%2C%20colors%2C%20images%2C%20text%2C%20margins)%20using%20the%20templates) 
  - Your design:
![main](https://user-images.githubusercontent.com/97834160/205600621-a8f3286a-69ad-48db-904a-3bbee5efcad2.png)


  - Figma:
![mainFig](https://user-images.githubusercontent.com/97834160/205600685-54a73f61-ad8e-4c1e-8d77-dfcb56d23e9b.png)

2022-12-06 17:18 UTC, RiyaBulia12 approved these changes
## STATUS: APPROVED 🏆🥇 

### Hi @valt19 👋🏽  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
#### Congratulations! 🎉 🎉 🥳 🥳 

<img src="https://user-images.githubusercontent.com/50941074/190630799-31045ee0-2625-4964-92fa-9e77f79f6fda.gif"/>

## Highlights
* No Linter errors ✔️
* Good commit messages ✔️
* Professional Readme file ✔️
* Descriptive PR ✔️
* GitHub flow used ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 17:18 UTC, RiyaBulia12 commented on index.html
> +    <title>Document</title>
- [ **OPTIONAL** ] How about having a title like '**My Portfolio**' or '**Portfolio**' that is relevant to the project instead of Document?

2022-12-06 17:18 UTC, RiyaBulia12 commented on index.html
> +        <img class="background-image"src="i-bttn/background-shapes/header-shapes mobile.png" alt="">
- [ **OPTIONAL** ] Please use css `background` image property instead of the `<img>` tag to give it more aesthetic view. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info.

2022-12-06 17:21 UTC, merged